using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;

namespace MonoGame.Editor.SourceGenerator;

/// <summary>
/// Lee ficheros adicionales <c>*.scene.json</c> y emite una clase de metadatos estática por escena.
/// Las clases generadas son compatibles con AOT (sin reflexión en tiempo de ejecución).
/// </summary>
[Generator]
public sealed class SceneSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<AdditionalText> sceneFiles =
            context.AdditionalTextsProvider
                   .Where(static f => f.Path.EndsWith(".scene.json", StringComparison.OrdinalIgnoreCase));

        context.RegisterSourceOutput(sceneFiles, static (ctx, file) =>
        {
            string? json = file.GetText()?.ToString();
            if (string.IsNullOrEmpty(json)) return;

            try
            {
                string source = GenerateSceneClass(file.Path, json!);
                string hintName = System.IO.Path.GetFileName(file.Path)
                    .Replace(".scene.json", "_Scene.g.cs");
                ctx.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "MGEDITOR001",
                        "Scene source generation failed",
                        $"Failed to generate code for {file.Path}: {ex.Message}",
                        "SceneGenerator",
                        DiagnosticSeverity.Warning,
                        isEnabledByDefault: true),
                    Location.None));
            }
        });
    }

    private static string GenerateSceneClass(string filePath, string json)
    {
        SceneData scene = ParseScene(json);

        string className = ToValidIdentifier(scene.Name.Length > 0 ? scene.Name : "UnnamedScene");
        string relPath = filePath.Replace('\\', '/');

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Source: {relPath}");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        sb.AppendLine($"/// <summary>Auto-generated metadata for scene <c>{scene.Name}</c>.</summary>");
        sb.AppendLine($"public static class {className}_Scene");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Scene display name.</summary>");
        sb.AppendLine($"    public const string Name = \"{Escape(scene.Name)}\";");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Relative path to the source scene JSON file.</summary>");
        sb.AppendLine($"    public const string Path = \"{Escape(relPath)}\";");
        sb.AppendLine();

        if (scene.Objects.Count > 0)
        {
            sb.AppendLine($"    /// <summary>Object names defined in this scene.</summary>");
            sb.AppendLine($"    public static class ObjectNames");
            sb.AppendLine("    {");
            HashSet<string> usedNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (ObjectData obj in scene.Objects)
                EmitObjectNameConst(sb, obj, usedNames, 8);
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    /// <summary>Returns metadata for all root objects in the scene.</summary>");
            sb.AppendLine($"    public static IEnumerable<SceneObjectMetadata> GetRootObjects()");
            sb.AppendLine("    {");
            foreach (ObjectData obj in scene.Objects)
                EmitObjectYield(sb, obj, 8);
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Lightweight metadata for a scene game object.</summary>");
        sb.AppendLine("public readonly struct SceneObjectMetadata");
        sb.AppendLine("{");
        sb.AppendLine("    public string Name     { get; }");
        sb.AppendLine("    public bool   Active   { get; }");
        sb.AppendLine("    public float  X        { get; }");
        sb.AppendLine("    public float  Y        { get; }");
        sb.AppendLine("    public float  Rotation { get; }");
        sb.AppendLine("    public SceneObjectMetadata(string name, bool active, float x, float y, float rotation)");
        sb.AppendLine("        => (Name, Active, X, Y, Rotation) = (name, active, x, y, rotation);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitObjectNameConst(StringBuilder sb, ObjectData obj, HashSet<string> used, int indent)
    {
        string pad = new string(' ', indent);
        string ident = ToValidIdentifier(obj.Name);
        if (!used.Add(ident))
            ident += "_" + Math.Abs(obj.Name.GetHashCode()).ToString();
        sb.AppendLine($"{pad}public const string {ident} = \"{Escape(obj.Name)}\";");
        foreach (ObjectData child in obj.Children)
            EmitObjectNameConst(sb, child, used, indent);
    }

    private static void EmitObjectYield(StringBuilder sb, ObjectData obj, int indent)
    {
        string pad = new string(' ', indent);
        string name = Escape(obj.Name);
        string active = obj.Active ? "true" : "false";
        sb.AppendLine($"{pad}yield return new SceneObjectMetadata(\"{name}\", {active}, {obj.X.ToString("G", System.Globalization.CultureInfo.InvariantCulture)}f, {obj.Y.ToString("G", System.Globalization.CultureInfo.InvariantCulture)}f, {obj.Rotation.ToString("G", System.Globalization.CultureInfo.InvariantCulture)}f);");
    }

    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string ToValidIdentifier(string name)
    {
        var sb = new StringBuilder();
        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }
        if (sb.Length == 0) return "_";
        if (char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }

    #region JSON parsing

    private static SceneData ParseScene(string json)
    {
        SceneData scene = new SceneData();
        try
        {
            using JsonDocument doc = JsonDocument.Parse(json);
            JsonElement root = doc.RootElement;

            if (root.TryGetProperty("name", out JsonElement nameEl))
                scene.Name = nameEl.GetString() ?? string.Empty;

            if (root.TryGetProperty("rootGameObjects", out JsonElement objsEl)
                && objsEl.ValueKind == JsonValueKind.Array)
            {
                foreach (JsonElement objEl in objsEl.EnumerateArray())
                    scene.Objects.Add(ParseObject(objEl));
            }
        }
        catch (JsonException)
        {
            // Devolver lo que se haya analizado hasta ahora
        }
        return scene;
    }

    private static ObjectData ParseObject(JsonElement el)
    {
        ObjectData obj = new ObjectData();

        if (el.TryGetProperty("name", out JsonElement nameEl))
            obj.Name = nameEl.GetString() ?? string.Empty;

        if (el.TryGetProperty("active", out JsonElement activeEl))
            obj.Active = activeEl.GetBoolean();

        if (el.TryGetProperty("position", out JsonElement posEl))
        {
            if (posEl.TryGetProperty("x", out JsonElement xEl)) obj.X = xEl.GetSingle();
            if (posEl.TryGetProperty("y", out JsonElement yEl)) obj.Y = yEl.GetSingle();
        }

        if (el.TryGetProperty("rotation", out JsonElement rotEl))
            obj.Rotation = rotEl.GetSingle();

        if (el.TryGetProperty("children", out JsonElement childrenEl)
            && childrenEl.ValueKind == JsonValueKind.Array)
        {
            foreach (JsonElement childEl in childrenEl.EnumerateArray())
                obj.Children.Add(ParseObject(childEl));
        }

        return obj;
    }

    private sealed class SceneData
    {
        public string Name { get; set; } = string.Empty;
        public List<ObjectData> Objects { get; } = new List<ObjectData>();
    }

    private sealed class ObjectData
    {
        public string Name { get; set; } = string.Empty;
        public bool Active { get; set; } = true;
        public float X { get; set; }
        public float Y { get; set; }
        public float Rotation { get; set; }
        public List<ObjectData> Children { get; } = new List<ObjectData>();
    }

    #endregion
}
